### ISSUE TITLE
[Bug] Failed to crash players

### ISSUE THREAD

**Issue by ghost** [Bram1903/MinecraftPlayerCrasher#11] opened 2024-05-15 10:40 UTC
example:

[12:38:38 INFO]: Attempting to crash Tetanek_110...
[12:38:38 INFO]: Failed to crash Tetanek_110!

Not all of them, but some are impossible
maybe it's after the update I can't crash some rule-breakers 

1.12.2 server

**Comment by F3F5** [comment] 2024-05-16 13:05
do you think all players have a "bypass" from crash

**Comment by Bram1903** [comment] 2024-05-16 15:06
> do you think all players have a "bypass" from crash

https://github.com/Bram1903/MinecraftPlayerCrasher/blob/c589fabaf110c6b0d087af8c845bc9218467c3b1/src/main/resources/plugin.yml#L29
No? 

Have you tried other methods as well, or are you only using `/crash player`? By default, it uses the explosion packet, but perhaps they specifically crash when using position or particle.

**Comment by F3F5** [comment] 2024-05-17 15:35
crash Tetanek_110 particle
[17:34:46 INFO]: Attempting to crash Tetanek_110...
[17:34:46 INFO]: Failed to crash Tetanek_110!
crash Tetanek_110 explosion
[17:34:51 INFO]: Attempting to crash Tetanek_110...
[17:34:51 INFO]: Failed to crash Tetanek_110!

**Comment by Bram1903** [comment] 2024-05-17 15:37
Is this on 1.12.2? Perhaps I can add a way to show you what client they are using. That wouldn't be 100% accurate as that can be spoofed from the client, but it could give an indication.

**Comment by F3F5** [comment] 2024-05-17 15:38
via says 1.12.2

**Comment by Bram1903** [comment] 2024-05-17 15:39
It could be that ViaVersion is causing issues, but I would have to test that.

**Comment by Bram1903** [comment] 2024-05-17 18:58
@F3F5,

I have a cool update on its way. I have to fix fetching the client brand for versions below 1.13, but that's about it. 
The new version automatically selects the best method based on the target of their client version, and it detects better if someone is crashed by increasing the delay between sending the transaction packets and the crash check. 

![image](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/70259613/e39a6f5c-5469-4b8f-b69b-72c427f736fa)

**Comment by F3F5** [comment] 2024-05-17 19:04
i love this
but some players didn't really crash

**Comment by Bram1903** [comment] 2024-05-17 19:55
> i love this but some players didn't really crash

I improved the checks if someone actually crashed because sometimes it said it failed, even though the player crashed, and vice versa. I also added that the plugin selects the best method for each client version, so if someone is on 1.8.8 it uses the Position method by default, and Explosion on 1.12.2, etc. It uses the client version for that, not the server version.

**Comment by Bram1903** [comment] 2024-05-18 11:01
@F3F5,

https://github.com/Bram1903/MinecraftPlayerCrasher/releases/tag/v2.5.0

I just released this new version. Could you try it out? It should have fixed most issues described in this issue. 

Kind regards,
Bram

**Comment by F3F5** [comment] 2024-05-18 12:43
the player has 1.16.5 vanilla optifine, but writes 1.16.4

**Comment by Bram1903** [comment] 2024-05-18 12:46
> the player has 1.16.5 vanilla optifine, but writes 1.16.4

That's normal. Some versions share them same protocol version. For example 1.20.6 is just 1.20.5 for the protocol version. There is no way to fix that, as that's just how that's being done by Mojang.

**Comment by F3F5** [comment] 2024-05-22 07:57
most people kick for timeout instead of crash

**Comment by Bram1903** [comment] 2024-05-22 08:26
> most people kick for timeout instead of crash

Hello,

Can you provide more details? The new fail message now also includes the brand and client versions of players. Without that information, there is no way for me to test this issue. You can also use `/crashinfo player` which will return their brand and version without sending a crash packet. 

Kind regards,
Bram

**Comment by Bram1903** [comment] 2024-05-22 12:20
> [11:01:13 INFO]: tm98 is running Fml,forge on Minecraft version 1.12.2.                              

You aren't specifying a method when trying to crash somebody right?

**Comment by F3F5** [comment] 2024-05-22 12:35
> > [11:01:13 INFO]: tm98 is running Fml,forge on Minecraft version 1.12.2.
> 
> You aren't specifying a method when trying to crash somebody right?

I've tried all the methods, the player is kicking for a timeout, maybe the fact is that you are sending a keepalive

**Comment by F3F5** [comment] 2024-05-30 20:04
my theory is confirmed, because of checking whether the player crashes - the player does not crash at all and
my friend and I were fanning on the test server, he has 1.12.2 forge optifine

**Comment by Bram1903** [comment] 2024-05-30 20:10
> my theory is confirmed, because of checking whether the player crashes - the player does not crash at all and
> 
> my friend and I were fanning on the test server, he has 1.12.2 forge optifine

Huh, that doesn't make any sense? The crash packet has already been sent at that point, thus it's not able to cancel it. I'll try and crash myself using Forge 1.12.2 with Optifine again tomorrow, but the last time I tested it, it worked fine.

**Comment by F3F5** [comment] 2024-06-01 19:47
what about this https://github.com/HaHaWTH/ClientBoomer/blob/main/src/main/java/io/wdsj/clientboomerpacketevents/PacketEventsPacketListener.java

**Comment by Bram1903** [comment] 2024-06-05 11:32
That URL isn't working.

**Comment by Bram1903** [comment] 2024-06-20 12:13
This will now be closed in favor of the rewrite. If this issue still occurs you can reopen it from your new account :-)

**Closed by Bram1903** 2024-06-20 12:13 UTC
Labels: bug
